=encoding utf-8

=head1 Der  Alltag eines CPAN Testers

  21:45 < nadim> history | wc -l => 500
  21:46 < nadim> history | grep test | wc -l => 375
  21:46 < nadim> I have to get a life!

=head1 Was ist ein CPAN Tester?

=over

=item * CPAN, CPAN::Reporter, CPAN::Reporter::Smoker

=item * CPANPLUS, CPAN::YACSmoke, POE::Component::CPAN::YACSmoke

=back

=head1 Warum teste ich?

Um Bugs zu finden, bevor Ihr sie findet.

=head1 URLs

=over

=item * http://cpantest.grango.org/

=item * http://cpantesters.perl.org/

=item * http://bbbike2.radzeit.de/~slaven/cpantestersmatrix.cgi

=item * http://www.nntp.perl.org/group/perl.cpan.testers/

  http://www.nntp.perl.org/group/perl.cpan.testers/2008/01/page1.html

  http://www.nntp.perl.org/group/perl.cpan.testers/2008/01/page84.html

  http://use.perl.org/~BinGOs/journal/35550

=item * http://cpandeps.cantrell.org.uk/?module=

=item * http://perl.grango.org/

=back

=head1 People

=over

=item * Adam J. Foxson

=item * Adam Kennedy

=item * Alexandr Ciornii

=item * Barbie

=item * Bingos (Chris Williams)

=item * David Cantrell

=item * David Golden

=item * Imacat

=item * Jost Krieger

=item * Mark Lehmann

=item * Ovid

I find it sad that so many companies have this tension between QA and
developers and here were are, seeing the EXACT same thing.

http://www.xray.mpe.mpg.de/mailing-lists/perl5-porters/2008-01/msg00722.html

=item * Sébastien Aperghis-Tramoni

=item * Slaven Rezić

=back

=head1 RT

=over

=item http://use.perl.org/~LaPerla/journal/35252

=item http://rt.cpan.org/Search/Build.html

=back

=head1 Konfigurieren

CPAN::Reporter schreibt das Ergebnis der interaktiven Konfiguration in
die Datei C<~/.cpanreporter/config.ini>. Im INI Format.

  cc_author=ask/no
  debug=1
  edit_report=ask/no
  editor=emacsclient
  email_from=andreas.koenig.gmwojprw@franz.ak.mind.de
  send_duplicates=ask/no
  send_report=ask/no
  smtp_server=localhost

In the works: C<cc_skipfile>, C<send_skipfile>

=head1 No SMTP, no Tester

Todo

=cut
