name: Matrix Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        perl: [ '5.36.0', '5.34.1', '5.32.1', '5.30.3', '5.28.3', '5.26.3', '5.24.4', '5.22.4', '5.20.3', '5.18.4', '5.16.3', '5.14.4', '5.12.5', '5.10.1' ]
    continue-on-error: ${{ matrix.os == 'windows-latest' && contains(fromJson('["5.20.3", "5.18.4", "5.16.3", "5.14.4", "5.12.5", "5.10.1"]'), matrix.perl) }}
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Test
        run: |
          perl -V
          cpanm -n Expect YAML CPAN::Perl::Releases
          perl Makefile.PL
          make touchtestdistros
          make test
